drop table if exists accounts;
create table items (
     id bigint generated by default as identity,
     login varchar(255) unique not null,
     name varchar(255),
     birthdate date,
     primary key (id)
);