server:
  port: 8086

bank:
  accounts:
    base-url: http://accounts-sd
    timeout: 4
  notification:
    base-url: http://notification-sd
    timeout: 4

spring:
  application:
    name: transfer

  cloud:
    consul:
      host: consul          # Адрес Consul (по умолчанию localhost)
      port: 8500               # Порт Consul (8500 по умолчанию)
      discovery:
        service-name: transfer-sd  # Необязательно, по умолчанию берётся spring.application.name
        prefer-ip-address: false
        hostname: transfer
      config:
        enabled: true            # Включаем Consul Config для внешней конфигурации
        prefix: config           # Префикс в KV-хранилище Consul (по умолчанию "config")
        defaultContext: application  # Контекст по умолчанию
  config:
    import: "optional:consul:"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_EXTERNAL_URL}/realms/bank-realm
          jwk-set-uri: ${KEYCLOAK_INTERNAL_URL}/realms/bank-realm/protocol/openid-connect/certs

      client:
        registration:
          transfer-service:
            provider: keycloak
            client-id: transfer-service
            client-secret:  ${KEYCLOAK_SECRET}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_INTERNAL_URL}/realms/bank-realm/protocol/openid-connect/token

resilience4j:
  circuitbreaker:
    instances:
      accountService:
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5
        slow-call-duration-threshold: 4s
        slow-call-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
      notificationService:
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5
        slow-call-duration-threshold: 4s
        slow-call-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true

  timelimiter:
    instances:
      accountService:
        timeout-duration: 5s
      notificationService:
        timeout-duration: 5s

  retry:
    instances:
      secondApp:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException$ServiceUnavailable
          - java.util.concurrent.TimeoutException
        ignore-exceptions:
          - java.lang.IllegalArgumentException