apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bank-front-app-chart.fullname" . }}-config
data:
  KC_AUTH_URI: {{ .Values.keycloak.auth_uri | quote }}
  KC_TOKEN_URI: {{ .Values.keycloak.token_uri | quote }}
  KC_JWK_URI: {{ .Values.keycloak.jwk_uri | quote }}
