global:
  kc_secret: <secret>

zipkin:
  enabled: true
  service:
    type: NodePort
    port: 9411
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
  ingress:
    enabled: true
    host: zipkin.local
    className: "traefik"
    annotations:
      kubernetes.io/ingress.class: "traefik"

kube-prometheus-stack:
  alertmanager:
    enabled: false

  grafana:
    defaultDashboardsEnabled: false
    adminPassword: admin

    service:
      type: NodePort
      nodePort: 30000

    persistence:
      enabled: true
      size: 1Gi

    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"

  prometheus:
    prometheusSpec:
      retention: 10d
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 20Gi