global:
  kc_secret: <secret>

zipkin:
  enabled: true
  service:
    type: NodePort
    port: 9411
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"

kube-prometheus-stack:
  alertmanager:
    enabled: false

  grafana:
    defaultDashboardsEnabled: true
    adminPassword: admin

    service:
      type: NodePort
      nodePort: 30000

    persistence:
      enabled: true
      size: 1Gi

  prometheus:
    prometheusSpec:
      retention: 10d
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 20Gi