server:
  port: 8087

topic:
  notification:
    name: ${TOPIC_NOTIFICATION_NAME}

spring:
  application:
    name: notification

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      group-id: yandex-practicum
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties.spring.json.trusted.packages: ru.yandex.practicum.notification.model
    listener:
      ack-mode: manual_immediate

logging:
  level:
    root: INFO
    ru.yandex.practicum.notification: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG
    org.springframework.security.authentication: DEBUG
    org.springframework.security.oauth2.client: DEBUG

#  file:
#    name: logs/notification.log

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %-5level - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
