server:
  port: 8087

spring:
  application:
    name: notification

#  cloud:
#    consul:
#      host: consul          # Адрес Consul (по умолчанию localhost)
#      port: 8500               # Порт Consul (8500 по умолчанию)
#      discovery:
#        service-name: notification-sd  # Необязательно, по умолчанию берётся spring.application.name
#        prefer-ip-address: false
#        hostname: notification
#      config:
#        enabled: true            # Включаем Consul Config для внешней конфигурации
#        prefix: config           # Префикс в KV-хранилище Consul (по умолчанию "config")
#        defaultContext: application  # Контекст по умолчанию
#  config:
#    import: "optional:consul:"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_EXTERNAL_URL}/realms/bank-realm
          jwk-set-uri: ${KEYCLOAK_INTERNAL_URL}/realms/bank-realm/protocol/openid-connect/certs

      client:
        registration:
          transfer-service:
            provider: keycloak
            client-id: transfer-service
            client-secret:  ${KEYCLOAK_SECRET}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_INTERNAL_URL}/realms/bank-realm/protocol/openid-connect/token

logging:
  level:
    root: INFO
    ru.yandex.practicum.notification: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG
    org.springframework.security.authentication: DEBUG
    org.springframework.security.oauth2.client: DEBUG

#  file:
#    name: logs/notification.log

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %-5level - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
