drop table if exists accounts;
create table accounts (
     id bigint generated by default as identity,
     login varchar(255) unique not null,
     name varchar(255),
     birthdate date,
     amount numeric(10,1),
     primary key (id)
);

insert into accounts (login, name, birthdate, amount)
values ('ivanov', 'Иванов Иван', '2025-10-25', 100);

insert into accounts (login, name, birthdate, amount)
values ('petrov', 'Петров Вася', '2001-08-25', 200);

insert into accounts (login, name, birthdate, amount)
values ('vasechkin', 'Васечкин Петя', '2001-06-10', 150);