drop table if exists app_accounts.accounts;
create table app_accounts.accounts (
     id bigint generated by default as identity,
     login varchar(255) unique not null,
     name varchar(255),
     birthdate date,
     amount integer,
     primary key (id)
);

insert into app_accounts.accounts (login, name, birthdate, amount)
values ('ivanov', 'Иванов Иван', '2025-10-25', 100);

insert into app_accounts.accounts (login, name, birthdate, amount)
values ('petrov', 'Петров Вася', '2001-08-25', 200);

insert into app_accounts.accounts (login, name, birthdate, amount)
values ('vasechkin', 'Васечкин Петя', '2001-06-10', 150);