apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accounts-chart.fullname" . }}-secret
  labels:
    {{- include "accounts-chart.labels" . | nindent 4 }}
type: Opaque
data:
  KC_SECRET: {{ .Values.global.kc_secret | b64enc | quote }}
  PG_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
