server:
  port: 8082

logging:
  level:
    root: INFO
    ru.yandex.practicum.accounts: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG
    org.springframework.security.authentication: DEBUG
    org.springframework.security.oauth2.client: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %-5level - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

topic:
  notification:
    name: ${TOPIC_NOTIFICATION_NAME}

spring:
  application:
    name: accounts

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    producer:
      acks: all
      enable-idempotence: true
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        delivery.timeout.ms: 120000
        retries: 2147483647

  datasource:
    url: ${PG_URL}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#        default_schema: app_accounts
        hbm2ddl:
          create_namespaces: true
    show-sql: true

#  sql:
#    init:
#      mode: always
#      data-locations: classpath:sql/data.sql

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_EXTERNAL_URL}/realms/bank-realm
          jwk-set-uri: ${KEYCLOAK_INTERNAL_URL}/realms/bank-realm/protocol/openid-connect/certs
#          issuer-uri: http://keycloak:30080/realms/bank-realm
#          jwk-set-uri: http://keycloak:8080/realms/bank-realm/protocol/openid-connect/certs

      client:
        registration:
          transfer-service:
            provider: keycloak
            client-id: transfer-service
            client-secret: ${KEYCLOAK_SECRET}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
#            token-uri: http://keycloak:8080/realms/bank-realm/protocol/openid-connect/token
            token-uri: ${KEYCLOAK_INTERNAL_URL}/realms/bank-realm/protocol/openid-connect/token

management:
  zipkin:
    tracing:
      endpoint: http://bank-zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: '*'
