server:
  port: 8082

spring:
  application:
    name: accounts

  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show-sql: true

    datasource:
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        connection-timeout: 20000
        idle-timeout: 300000
        max-lifetime: 1200000

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bank-realm

      client:
        registration:
          transfer-service:
            provider: keycloak
            client-id: transfer-service
            client-secret: ZY4fuQa2weoz2SV60g6kberJPoMX9rxd
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/bank-realm
