server:
  port: 8082

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG
    org.springframework.security.authentication: DEBUG
    org.springframework.security.oauth2.client: DEBUG

bank:
  notification:
    base-url: ${NOTIFICATION_URL}
#    base-url: http://notification-sd
    timeout: 4

spring:
  application:
    name: accounts

#  datasource:
#    url: jdbc:postgresql://postgres:5432/mydb?currentSchema=app_accounts
#    username: myuser
#    password: mypassword
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 5
#      connection-timeout: 20000
#      idle-timeout: 300000
#      max-lifetime: 1200000
#      schema: app_accounts

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#        default_schema: app_accounts
        hbm2ddl:
          create_namespaces: true
    show-sql: true

  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_EXTERNAL_URL}/realms/bank-realm
          jwk-set-uri: ${KEYCLOAK_INTERNAL_URL}/realms/bank-realm/protocol/openid-connect/certs
#          issuer-uri: http://keycloak:30080/realms/bank-realm
#          jwk-set-uri: http://keycloak:8080/realms/bank-realm/protocol/openid-connect/certs

      client:
        registration:
          transfer-service:
            provider: keycloak
            client-id: transfer-service
            client-secret: bQimy9NFoZnDk9S5QJNrG8zM7YEaZ2PV
#            client-secret: ${KEYCLOAK_SECRET}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
#            token-uri: http://keycloak:8080/realms/bank-realm/protocol/openid-connect/token
            token-uri: ${KEYCLOAK_INTERNAL_URL}/realms/bank-realm/protocol/openid-connect/token

resilience4j:
  circuitbreaker:
    instances:
      notificationService:
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5
        slow-call-duration-threshold: 4s
        slow-call-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true

  timelimiter:
    instances:
      notificationService:
        timeout-duration: 5s

  retry:
    instances:
      secondApp:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException$ServiceUnavailable
          - java.util.concurrent.TimeoutException
        ignore-exceptions:
          - java.lang.IllegalArgumentException