apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway-chart.fullname" . }}-config
data:
  KEYCLOAK_EXTERNAL_URL: {{ .Values.keycloak.external_url | quote }}
  KEYCLOAK_INTERNAL_URL: {{ .Values.keycloak.internal_url | quote }}
  ACCOUNTS_URL: {{ .Values.accounts_url | quote }}
  CASH_URL: {{ .Values.cash_url | quote }}
  TRANSFER_URL: {{ .Values.transfer_url | quote }}
