replicaCount: 1

image:
  repository: bank-front-app
  pullPolicy: IfNotPresent
  tag: "latest"

keycloak:
  auth_uri: http://keycloak
  token_uri: http://keycloak:8080
  jwk_uri: http://keycloak:8080

gateway_url: http://bank-gateway.default.svc.cluster.local
#accounts_url: http://bank-accounts-chart.default.svc.cluster.local
#cash_url: http://bank-cash-chart.default.svc.cluster.local
#transfer_url: http://bank-transfer-chart.default.svc.cluster.local

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8084
#  targetPort: 8084
#  nodePort: 8084

ingress:
  enabled: true
  className: "traefik"
  hosts:
    - host: bank.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

test:
  enabled: false

httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
  - name: gateway
    sectionName: http
  hostnames:
  - chart-example.local
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /headers

resources: {}

startupProbe:
  initialDelaySeconds: 20
  failureThreshold: 10
  httpGet:
    path: /actuator/health
    port: 8084
livenessProbe:
  initialDelaySeconds: 20
  failureThreshold: 10
  httpGet:
    path: /actuator/health
    port: 8084
readinessProbe:
  initialDelaySeconds: 20
  failureThreshold: 10
  httpGet:
    path: /actuator/health
    port: 8084

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
