replicaCount: 1

image:
  repository: accounts
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8082
#  nodePort: 30082

keycloak:
  external_url: http://keycloak
  internal_url: http://keycloak:8080

notification_url: http://notification-chart.default.svc.cluster.local

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

#ingress:
#  enabled: false
#  className: "traefik"
#  annotations: {}
#  hosts:
#    - host: accounts
#      paths:
#        - path: /accounts
#          pathType: Prefix

httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - chart-example.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /headers

resources: {}

startupProbe:
  initialDelaySeconds: 20
  failureThreshold: 10
  httpGet:
    path: /actuator/health
    port: 8082
livenessProbe:
  initialDelaySeconds: 20
  failureThreshold: 10
  httpGet:
    path: /actuator/health
    port: 8082
readinessProbe:
  initialDelaySeconds: 20
  failureThreshold: 10
  httpGet:
    path: /actuator/health
    port: 8082

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

