replicaCount: 1

image:
  repository: gateway
  pullPolicy: IfNotPresent
  tag: "latest"

keycloak:
  external_url: http://keycloak
  internal_url: http://keycloak:8080

accounts_url: http://bank-accounts.default.svc.cluster.local
cash_url: http://bank-cash.default.svc.cluster.local
transfer_url: http://bank-transfer.default.svc.cluster.local

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8081

#ingress:
#  enabled: false
#  className: ""
#  annotations: {}
#  hosts:
#    - host: chart-example.local
#      paths:
#        - path: /
#          pathType: ImplementationSpecific
#  tls: []


httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
  - name: gateway
    sectionName: http
  hostnames:
  - chart-example.local
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /headers

resources: {}

startupProbe:
  initialDelaySeconds: 20
  failureThreshold: 10
  httpGet:
    path: /actuator/health
    port: 8081
livenessProbe:
  initialDelaySeconds: 20
  failureThreshold: 10
  httpGet:
    path: /actuator/health
    port: 8081
readinessProbe:
  initialDelaySeconds: 20
  failureThreshold: 10
  httpGet:
    path: /actuator/health
    port: 8081

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
