apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-custom-dashboard
  labels:
    grafana_dashboard: "1"

data:
  sprint-boot.json: |-
{{ .Files.Get "dashboard/spring-boot.json" | indent 4 }}
  bank-front-app.json: |-
{{ .Files.Get "dashboard/bank-front-app.json" | indent 4 }}
