{
 "title": "Bank-front-app",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cash",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(login, __name__) (cash_total)",
     "legendFormat": "{{__name__}} {{login}}"
    },
    {
     "expr": "sum by(login, __name__) (cash_fail_total)",
     "legendFormat": "{{__name__}} {{login}}"
    }
   ]
  },
  {
   "title": "Transfer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(senderLogin, recipientLogin, __name__) (transfer_total)",
     "legendFormat": "{{__name__}} {{login}}"
    },
    {
     "expr": "sum by(senderLogin, recipientLogin, __name__) (transfer_fail_total)",
     "legendFormat": "{{__name__}} {{login}}"
    }
   ]
  },
  {
   "title": "Notification",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(login, __name__) (notification_total)",
     "legendFormat": "{{__name__}} {{login}}"
    },
    {
     "expr": "sum by(login, __name__) (notification_fail_total)",
     "legendFormat": "{{__name__}} {{login}}"
    },
    {
     "expr": "sum by(login, __name__) (notification_success_total)",
     "legendFormat": "{{__name__}} {{login}}"
    }
   ]
  }
 ]
}