apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transfer-chart.fullname" . }}-secret
  labels:
    {{- include "transfer-chart.labels" . | nindent 4 }}
type: Opaque
data:
  KC_SECRET: {{ .Values.global.kc_secret | b64enc | quote }}
