replicaCount: 1

image:
  repository: notification
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8087

keycloak:
  external_url: http://keycloak
  internal_url: http://keycloak:8080

kafka:
  servers: kafka-broker-0.kafka-headless.default.svc.cluster.local:9092
  topic:
    notification:
      name: log-events

httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - chart-example.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /headers

resources: {}

startupProbe:
  initialDelaySeconds: 20
  failureThreshold: 10
  httpGet:
    path: /actuator/health
    port: 8087
livenessProbe:
  initialDelaySeconds: 20
  failureThreshold: 10
  httpGet:
    path: /actuator/health
    port: 8087
readinessProbe:
  initialDelaySeconds: 20
  failureThreshold: 10
  httpGet:
    path: /actuator/health
    port: 8087

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
